server:
  port: 19092

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"  # Zipkin 설정
  tracing:
    sampling:
      probability: 1.0  # Zipkin 설정
  endpoints:
    web:
      exposure:
        include: refresh  # [Post] /actuator/refresh 엔드포인트 노출 (config server 변경사항 수동 갱신)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MSA_Order_App
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true