
server:
  port: 19095

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    access-expiration: 3600000
    secret-key: "TGV0cyBzdGFydCBNU0EgcHJvamVjdA=="

